[package]
name = "ksp"
version = "0.1.0"
edition = "2024"

[dependencies]

[[bin]]
name = "please_wait"
path = "src/bin/2025/fall/please_wait.rs"

[[bin]]
name = "down_the_hill"
path = "src/bin/2025/fall/down_the_hill.rs"
